variable "enabled" {
  description = "When true, provisions the GatewaySubnet, public IP, and Virtual Network Gateway. The gateway is the single most expensive resource in this module (~USD 140/month for VpnGw1) and provisioning takes 30-45 minutes, so this defaults to false. Flip to true only while you actively need the tunnel."
  type        = bool
  default     = false
}

variable "project_name" {
  description = "Project short name."
  type        = string
}

variable "environment" {
  description = "Environment name (dev/staging/production)."
  type        = string
}

variable "location" {
  description = "Azure region."
  type        = string
}

variable "resource_group_name" {
  description = "Resource group that will own the gateway, public IP, and GatewaySubnet."
  type        = string
}

variable "virtual_network_name" {
  description = "Name of the existing VNet that the GatewaySubnet should be added to."
  type        = string
}

variable "gateway_subnet_prefix" {
  description = "CIDR for the GatewaySubnet. Must be at least /29; /27 is recommended by Azure."
  type        = list(string)
  default     = ["10.0.255.0/27"]

  validation {
    condition     = length(var.gateway_subnet_prefix) == 1
    error_message = "Provide exactly one CIDR for the GatewaySubnet."
  }
}

variable "vpn_client_address_pool" {
  description = "CIDR that Azure assigns to connected P2S clients. Must not overlap with the VNet, AKS, database, Redis, or any peered range."
  type        = string
  default     = "172.16.201.0/24"
}

variable "gateway_sku" {
  description = "Virtual Network Gateway SKU. Basic does not support OpenVPN; the smallest SKU that does is VpnGw1AZ. As of 2026 Azure no longer accepts new non-AZ VPN Gateways (NonAzSkusNotAllowedForVPNGateway), so only the *AZ variants are valid."
  type        = string
  default     = "VpnGw1AZ"

  validation {
    condition     = contains(["VpnGw1AZ", "VpnGw2AZ", "VpnGw3AZ"], var.gateway_sku)
    error_message = "gateway_sku must be one of the AZ SKUs that support OpenVPN P2S (VpnGw1AZ, VpnGw2AZ, VpnGw3AZ). Non-AZ SKUs (VpnGw1/2/3) are no longer accepted by Azure for new VPN gateways."
  }
}

variable "gateway_generation" {
  description = "Gateway hardware generation. Generation1 is the correct value for VpnGw1/VpnGw2/VpnGw3 and for VpnGw1AZ. Generation2 is only valid in combination with VpnGw2AZ or VpnGw3AZ. The module's lifecycle precondition catches obvious mispairings at plan time."
  type        = string
  default     = "Generation1"

  validation {
    condition     = contains(["Generation1", "Generation2"], var.gateway_generation)
    error_message = "gateway_generation must be either \"Generation1\" or \"Generation2\"."
  }
}

variable "root_certificate_name" {
  description = "Logical name Azure will display for the trusted root certificate."
  type        = string
  default     = "octoeshop-codespaces-root"
}

variable "root_certificate_public_data" {
  description = "Base64 body of the trusted root certificate (PEM without -----BEGIN/END----- markers and without line breaks). Generated by scripts/generate-codespaces-vpn-cert.sh. Empty string is allowed when enabled = false."
  type        = string
  default     = ""
}

variable "tags" {
  description = "Resource tags."
  type        = map(string)
  default     = {}
}
